apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gfcnsu9aj-python 
  janus-idp.io/tekton: gfcnsu9aj-python
  backstage.io/kubernetes-id: gfcnsu9aj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gfcnsu9aj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml